version: 2
jobs:
  build:
    docker:
      - image: alpine:latest

    working_directory: ~/repo

    steps:
      - run: apk add openssh docker

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build -t magnet:$CIRCLE_SHA1 .
