version: 2
jobs:
  build:
    docker:
      - image: alpine:latest

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: docker build -t magnet:$CIRCLE_SHA1 .
